# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Framehood < Formula
  desc "Framehood CLI — generate images, video and audio from your terminal."
  homepage "https://framehood.ai"
  version "0.2.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.2.1/framehood_darwin_amd64.tar.gz"
      sha256 "88550b645d82825bda37b6fa7ad8db7e77aadfaa94b926c412880ee98ad18e0c"

      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.2.1/framehood_darwin_arm64.tar.gz"
      sha256 "e83eacf0f1ec911d2b0ed173dcdf2a632f31110f670b340b0cd0f42de6860fb1"

      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.2.1/framehood_linux_amd64.tar.gz"
      sha256 "8538c8aa452b68058620f9b43ac05cb2ab5c948b835d5219ccaa17e1191d3dbc"
      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.2.1/framehood_linux_arm64.tar.gz"
      sha256 "200f7f2c500f106bc398534c790a3fae8ac4f4212f23f6842ef55214ee3765c1"
      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  test do
    system "#{bin}/framehood", "--version"
  end
end
