# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Framehood < Formula
  desc "Framehood CLI — generate images, video and audio from your terminal."
  homepage "https://framehood.ai"
  version "0.3.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.7/framehood_darwin_amd64.tar.gz"
      sha256 "8f6e2d2381d268f5cf08fa2f9c8ae8882cc51ca3ab6ad9509c7f0c9572c3ad31"

      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.7/framehood_darwin_arm64.tar.gz"
      sha256 "917e248de1ec809d250c6d3d7e01e158bd1f63068ad03abacbdfcafaa7e2ee90"

      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.7/framehood_linux_amd64.tar.gz"
      sha256 "a8d1eb6940e6a0ca8fe5137eccff6af5124dc7804563ab657fb0171722945e83"
      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.7/framehood_linux_arm64.tar.gz"
      sha256 "9c64d3506c6f92017abca91a28abf6ebe2dc25fb76ecb80cc8e82fee4926bd85"
      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  test do
    system "#{bin}/framehood", "--version"
  end
end
