# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Framehood < Formula
  desc "Framehood CLI — generate images, video and audio from your terminal."
  homepage "https://framehood.ai"
  version "0.3.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.4/framehood_darwin_amd64.tar.gz"
      sha256 "31344cfbc8fa6f9272fc0c13188b6587530017846f5a2d6c5b8234b1ff99731a"

      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.4/framehood_darwin_arm64.tar.gz"
      sha256 "65e72f3d040982b8698747797fdd07ba59ba93913c341f1cac3d3b87b2dadc88"

      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.4/framehood_linux_amd64.tar.gz"
      sha256 "02574b218b8f53616a550888f93c6e5954a21d6d7ae1e26b6b8b52d081edc805"
      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.4/framehood_linux_arm64.tar.gz"
      sha256 "16698139f95b03d4f4049b55df09e633fc7a8efde1bfa871da782980091566f9"
      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  test do
    system "#{bin}/framehood", "--version"
  end
end
