# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Framehood < Formula
  desc "Framehood CLI — generate images, video and audio from your terminal."
  homepage "https://framehood.ai"
  version "0.3.6"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.6/framehood_darwin_amd64.tar.gz"
      sha256 "fbcdca3f1f6ea6d60507748ae8d31953f1299de8e797e58cc6c23d89ee6c4908"

      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.6/framehood_darwin_arm64.tar.gz"
      sha256 "0745fadc325a12dd0cb64dad06534faf421173b303811db774702ade19ba2795"

      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.6/framehood_linux_amd64.tar.gz"
      sha256 "555e18003b76b46d6dc7986503e2954a937e3210d6dca9012832a9cce835fc71"
      define_method(:install) do
        bin.install "framehood"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Framehood/framehood-cli/releases/download/v0.3.6/framehood_linux_arm64.tar.gz"
      sha256 "f87a35cbb96763b8641804a3c0309c6501f53114cc675a57f3c3ec64d7f6e35b"
      define_method(:install) do
        bin.install "framehood"
      end
    end
  end

  test do
    system "#{bin}/framehood", "--version"
  end
end
